const coins = new Schema(
  {
    logo: { type: String },
    name: { type: String },
    symbol: { type: String },
    network: { type: String },
    description: { type: String },
    contract: { type: String },
    launchdate: { type: String },
    presaledate: { type: String },
    presaleenddate: { type: String },
    customchart: { type: String },
    customswap: { type: String },
    telegram: { type: String },
    website: { type: String },
    twitter: { type: String },
    telegramuser: { type: String },
    email: { type: String },
    discord: { type: String },
    telegramchat: { type: String },
    presale: { type: String },
    coinmarketcap: { type: String },
    coingecko: { type: String },
    status: { type: Boolean, default: false },
    presaledate: { type: String },
    price: { type: String },
    change24h: { type: String },
    lauch: { type: String },
    boosts: { type: String },
    coinUrl: { type: String },
    kyc: { type: Boolean, default: false },
    audit: { type: Boolean, default: false },
    promoted: { type: Boolean, default: false },
    presalelink: { type: String },

    date: { type: String, default: moment().format("DD MMMM YYYY HH:mm:ss") }, // son kontrol tarihi
  },
  { colection: "coins" },
);

module.exports = mongoDB.model("coins", coins);
